# Generated by Django 3.1.4 on 2021-02-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_like_is_match'),
        ('chat', '0002_remove_message_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like', to='like.like'),
            preserve_default=False,
        ),
    ]
