# Generated by Django 3.1.4 on 2021-01-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('like', '0002_auto_20210119_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.profile'),
        ),
    ]
