# Generated by Django 3.1.4 on 2021-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_auto_20210121_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
    ]
